### PR TITLE
add mock method and fix test.

### PR DESCRIPTION
**Pull request by cimadai**
## What is this pull request?
Add missing mock method and fix some tests.
   
## Why do you implement it? Why do we need this pull request?

There is missing mock mothod for test.
  
## How to use the features provided in the pull request?

cmake --build build --target test

## Details/Features
List of features / major commits
- Add mock method to ametsuchi_mocks.hpp
- Add test to command_validate_execute_test.cpp

### CODE REVIEW

**Comment by Warchant** [comment]
Sorry, we are currently playing with travis-ci, so it may not work now.

Regarding Circle CI - sometimes g++ throws "internal C++ error".
Whenever it happens -- just press "rebuild" on Circle CI. 
We will investigate why it happens.

**Comment by cimadai** [comment]
I understood. I'm waiting for completion for travis ci.
By the way, I cannot push "rebuild" button due to lack of my permissions. 
CircleCI shows `You need write permissions to trigger builds.`.

**Comment by cimadai** [comment]
I'm sorry.
The reason was that I'm not connected to GitHub account in CircleCI.

**Comment by l4l** [comment]
Seems ci is [liked it](https://circleci.com/gh/hyperledger/iroha/4775)

**Comment by takemiyamakoto** [comment]
What is the status of this PR?

**Comment by neewy** [comment]
After review, community manager, architecture owner and scientific researcher made a following decision:
tests are duplicated, a non-existent method is mocked. This pull request is closed.

**Pull request closed without merging**
